name: Build and Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  compilar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependências
        run: dotnet restore MyMuscles.sln

      - name: Build
        run: dotnet build MyMuscles.sln --no-restore --configuration Release
